apiVersion: v1
kind: Service
metadata:
  name: fake-datadog
  namespace: datadog-agent
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: api
  - port: 27017
    protocol: TCP
    targetPort: 27017
    name: mongo
  selector:
    app: fake-datadog
  type: ClusterIP