apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: datadog-agent
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd-autodicovery
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
          - {containerPort: 80, name: http, protocol: TCP}
