apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
  namespace: datadog-agent
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 1
  template:
    metadata:
      name: wildfly
      labels:
        app: wildfly
      annotations:
        ad.datadoghq.com/tolerate-unready: "true"
    spec:
      containers:
      - image: wildfly-jmx
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
          - {containerPort: 80, name: http, protocol: TCP}
          - {containerPort: 9990}
